import Head from 'next/head'
import type { ReactElement } from 'react'
import type { NextPageWithLayout } from './_app'
import HomeLayout from '@/components/layout/HomeLayout'
import HomePage from '@/features/home/pages/HomePage'

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <HomePage />
    </>
  )
}

Home.getLayout = function getLayout(page: ReactElement) {
  return <HomeLayout>{page}</HomeLayout>
}

export default Home
